name: portfolio_v2
description: "Vahid Rajabi Portfolio"
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  jiffy: ^6.3.1
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  injectable: ^2.4.4
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  go_router: ^14.2.7
  flutter_bloc: ^8.1.6
  meta: any
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.2.1
  url_launcher: ^6.3.0
  supabase_flutter: ^2.7.0
  flutter_dotenv: ^5.1.0
  widget_component_annotation: ^1.0.1
  bloc_concurrency: ^0.2.5
  bloc_test: ^9.1.7
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  bloc_test: ^9.1.7
  widget_component: 1.0.3

flutter:
  uses-material-design: true


  assets:
    - .env
    - assets/images/gif/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/jpg/
#    - assets/l10n/
#    - assets/images/png/
#    - assets/images/jpg/
#    - assets/images/projects/
#    - assets/images/projects/covers/
#    - assets/images/projects/clusterix_livechat/
#    - assets/images/projects/clusterix_email/
#    - assets/images/projects/clusterix_time_tracker/
#    - assets/images/projects/wallito/
#    - assets/images/projects/damapa/
#    - assets/images/projects/fanoos/
#    - assets/images/projects/kidora/
#    - assets/images/projects/polaris_vpn/
#    - assets/images/projects/poshtiban_yar/
#    - assets/images/projects/put_mobile_banking/
#    - assets/images/projects/unicom/
#    - assets/web/
