name: Portfolio Page CI/CD

on:
  push:
    branches:
      - main
      - cicd
  pull_request:
    branches:
      - main
      - cicd

jobs:
  ci:
    name: build page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel : 'stable'
          flutter-version: 3.24.0

      - name: Install dependencies
        run: flutter pub get

  deploy:
    runs-on: ubuntu-latest
    needs: ci
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0


      - name: Install dependencies
        run: flutter pub get

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_ANNO_KEY: ${{ secrets.ANNO_KEY }}
          envkey_SERVER_URL: ${{ secrets.SERVER_URL }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false


      - name: Build the web project
        run: flutter build web --web-renderer canvaskit

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none
